### ISSUE TITLE
Hyper-V support? 

### ISSUE THREAD

**Issue by MihaMarkic** [amaneureka/AtomOS#37]
I see there is VMware specific code in there. But will it run under Hyper-V as well? The thing is if you have the latter enabled you can't easily switch to the former and the other way round.

**Comment by amaneureka** [comment]
I don't think there is any VMware specific code. Could you link me? (if I missed)
I don't have any plans for Hyper-V right now.

**Comment by MihaMarkic** [comment]
Here, [video driver for VMWare](https://github.com/amaneureka/AtomOS/tree/master/src/Kernel/Kernel_alpha/Drivers/Video/Vmware).

**Comment by amaneureka** [comment]
Yes, that is a part of old kernel which is used for driver testing. I completed a more generic driver in [Kernel_H](https://github.com/amaneureka/AtomOS/tree/master/src/Kernel/Atomix.Kernel_H) So not using it anymore.

**Comment by MihaMarkic** [comment]
Ah, ok. So, you are saying that AtomOS won't run under Hyper-V or you just don't have any specific code for it?

**Comment by amaneureka** [comment]
It will surely run on Hyper-V. But I don't have any plans to specifically work on that "idea" and check supportable features and add specific code for that.

**Comment by MihaMarkic** [comment]
Sounds OK to me. Thanks.
