### ISSUE TITLE
Standard Library

### ISSUE THREAD

**Issue by Lewiscowles1986** [amaneureka/AtomOS#38]
Where is the standard library for C#? AFAIK compiling most C# projects requires a standard library / set of API's to do anything useful.

**Comment by SplittyDev** [comment]
The custom compiler built by the AtomOS team handles a small subset of the C#/IL functionality and the rest of the functions are plugged. That means, that they are implemented using that subset of the library that works with the compiler, and the original function calls are then replaced with the plugs.

The original .NET framework is not available, only the plugged subset of the framework.

**Comment by amaneureka** [comment]
This should clear your doubts
https://github.com/amaneureka/AtomOS/tree/master/src/Compiler/Atomixilc/Lib

**Comment by Lewiscowles1986** [comment]
@SplittyDev The first thing I thought when I heard about the OS was, "Is it an OS or an app?" followed by "How will the kernel run without a C# runtime?" (I thought it compiled to IL / Bytecode.) I looked through the code and tbh didn't find the plugs, so I raised this. It's still a very cool idea and thanks for the link to the lib @amaneureka

So really there are a few projects (big-picture):

* Re-implementing C#
* Writing a kernel
* Writing drivers
* porting libs & sw

**Comment by amaneureka** [comment]
Right. I'll include a page on compiler working on wiki itself. (noted)

**Comment by amaneureka** [comment]
@Lewiscowles1986  Please check this wiki page. [Compiler](https://github.com/amaneureka/AtomOS/wiki/Compiler)

**Comment by jtgame5** [comment]
Okay

**Comment by Lewiscowles1986** [comment]
That is some of the nicest documentation, closing :wink:
