### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by hadi77ir** [amaneureka/AtomOS#39]
Is the whole project licensed under BSD 3-clause, or some parts are just shared-source? (like Atomix.Core, Atomix.Shell, etc.)

Please make this clear.
Thanks.

**Comment by amaneureka** [comment]
whole project is licensed under "BSD 3-clause" You can find "complete project license" [here](https://github.com/amaneureka/AtomOS/blob/master/LICENSE.md)

**Comment by meineerde** [comment]
@amaneureka In that case, it is probably advisable to change the license headers in your source files. Currently each source file I checked contains the following comment on top:

> LICENSE:          Copyright (C) Atomix Development, Inc - All Rights Reserved
>                   Unauthorized copying of this file, via any medium is
>                   strictly prohibited Proprietary and confidential.

This implies strong copyright instead the quite liberal BSD-license. In a strict sense, the header implies much stricter rules and would probably supersede the license file in the repository root.

**Comment by amaneureka** [comment]
Fixed d5db4314e7b4e097b5c46fb95e5904e2e9e4b063
Closing issue!

Thanks

**Comment by meineerde** [comment]
Thanks!
