### ISSUE TITLE
Installer ISO

### ISSUE THREAD

**Issue by Bluscream** [amaneureka/AtomOS#42]
How to install this OS and is it supporting .NET binaries?

**Comment by amaneureka** [comment]
> How to install this OS

Because project is still in development you can try latest test build by building it from source code [Wiki](https://github.com/amaneureka/AtomOS/wiki/Build-Environment)

> is it supporting .NET binaries

Not really

**Comment by Bluscream** [comment]
What's the reason for it to be .net or C Sharp then

**Comment by amaneureka** [comment]
.NET are specific to windows platform. But any C# code/library compiled using [Atomix Compiler](https://github.com/amaneureka/AtomOS/wiki/Compiler) will work.

**Comment by Bluscream** [comment]
Who was the US made for what kind of users I mean is it true a production lol I can't replace Ubuntu or Windows or is it more like a devil Upland operating system

**Comment by Bluscream** [comment]
Sorry speech to text is worse then google translate :D

**Comment by amaneureka** [comment]
Seems like topic of this issue is now closed. You can discuss about project on IRC channel. Join me in ```#atomos``` on ```freenode.net```
