### ISSUE TITLE
[Travis] Cron Job

### ISSUE THREAD

**Issue by amaneureka** [amaneureka/AtomOS#45]
- [x] Toolchain Building
- [x] Libraries Building
- [x] Solution Compilation
- [x] Kernel Compilation

**Comment by fraser125** [comment]
I would like to clarify/suggest that deployment means a "release" available for download here github.com. Thank!!

**Comment by amaneureka** [comment]
> I would like to clarify/suggest that deployment means a "release" available for download

Indeed I meant that only. Deploy ISO image to either FTP or github release itself

**Comment by amaneureka** [comment]
It is fixed after using Travis trusty distribution environment
https://github.com/travis-ci/travis-ci/issues/7439#issuecomment-285017312

Commit 96a7d4d4b4fcd2131072a2a3aa4f679101d95ebf
