### ISSUE TITLE
[Build] Setup.sh --newlib fails when automake is above v1.12

### ISSUE THREAD

**Issue by aeleos** [amaneureka/AtomOS#46]
Newlib will fail to build when automake is below version 1.12, when doing the autoreconf command it will fail with the error:
`configure.in:5: error: support for Cygnus-style trees has been removed
`
Maybe have some kind of warning, as by default automake 1.14 is installed on ubuntu 14.04, and automake 1.15 is install on ubuntu 16.04. It can be fixed by removing the default package and installing the package automake1.1

**Comment by amaneureka** [comment]
Yes! a different version of automake and autoconf is required for building. try ```Setup.sh --setup``` It will building everything for you

**Comment by amaneureka** [comment]
It's GCC and Binutils requirement.

**Comment by aeleos** [comment]
`Setup.sh --setupSetup.sh --setup` still fails, which was how I originally discovered the problem, but I eventually tracked down the problem to newlib failing to build.

**Comment by aeleos** [comment]
When I say still I mean with the wrong version of automake, it fixed the problem for me when I installed automake1.1 instead.

**Comment by amaneureka** [comment]
```Setup.sh``` is building automake1.12 from source. then why you installed automake manually?

**Comment by aeleos** [comment]
It seems like during the newlib compilation on line 167 when it is running `autoreconf` it was using my system version instead of the compiled one.

**Comment by amaneureka** [comment]
Could you check manually ```which autoreconf``` just before line 167.

**Comment by aeleos** [comment]
Yep `which autoreconf` outputs /usr/bin/autoreconf

**Comment by mananpal1997** [comment]
I'm facing the same issue, I think. Shall I remove all automake versions?

**Comment by amaneureka** [comment]
that's weird! here it is ```/cygdrive/f/dev/Atomix/src/Build/Local/bin/autoreconf```
try two things
check if autoreconf exist in ```Build\Local\bin``` and this path exist in your ```PATH``` variable.

**Comment by aeleos** [comment]
Just running `sudo apt-get remove automake` and `sudo apt-get install automake1.1` fixed it for me.

**Comment by amaneureka** [comment]
> Just running `sudo apt-get remove automake` and `sudo apt-get install automake1.1` fixed it for me.

I really not suggest this. This could break many other system libraries. that is why ```Setup.sh``` is building stuffs in different directory.

**Comment by mananpal1997** [comment]
> check if autoreconf exist in Build\Local\bin and this path exist in your PATH variable.

Its there in Build/Local/bin but doesn't exist in PATH variable

**Comment by aeleos** [comment]
Just checked it, autoreconf exists in `Build\Local\bin` and it is in my PATH directory. Maybe changing the name of the binary would help, maybe something similar to the i386-atomos that is infront of some of the other binaries.

**Comment by amaneureka** [comment]
> Just checked it, autoreconf exists in `Build\Local\bin` ...

In case of conflicts. System always pick the first binary it encounter. Check ```Setup.sh```
It should read something like this ```export PATH=/usr/bin:$PREFIX/bin:$PATH``` line 10

> Its there in Build/Local/bin but doesn't exist in PATH variable

Are you running it correctly?

**Comment by aeleos** [comment]
I wrote that it **does** exist in my PATH variable. `/home/user/AtomOS/src/Build/Local/bin` That was copy pasted from my path with my username removed.

**Comment by aeleos** [comment]
if the system picks the first binary it encounters, and in the export you have /usr/bin first, wouldn't that confirm that it will always use the system autoreconf and not the one in `Build/Local/bin`?

**Comment by amaneureka** [comment]
Fine. I didn't notice. I don't have system autoconf installed in that ```PATH``` so it never occurred to me.
I'll make a fix commit. Thanks!

**Comment by aeleos** [comment]
No problem, happy to help.

**Comment by amaneureka** [comment]
@aeleos Can you please confirm if it is working now?

**Comment by mananpal1997** [comment]
It's fixed now.
