### ISSUE TITLE
Build failed. Please check the logs above to see what went wrong.

### ISSUE THREAD

**Issue by negator92** [amaneureka/AtomOS#49]
My PC:
http://pastebin.com/q7HGfYti

All I did is:
sudo apt-get install build-essential texinfo flex bison
than check packages, seems all needed already installed
chown +x Setup.sh from src/Build/ and run with sudo

some last lines from my terminal:
AtomOS/src/Build/Temp/newlib-1.19.0/newlib/doc/makedoc.c:1349:15: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     isp[0] = *(int *)(isp[0]);
               ^
i386-atomos-ar: creating libnosys.a
~/AtomOS/src/Build/Bin ~/AtomOS/src/Build
./Setup.sh: line 178: nasm: command not found
Build failed. Please check the logs above to see what went wrong.

Setup.log download:
http://www.mediafire.com/file/8dte5x3ohzw56n4/Setup.log

**Comment by amaneureka** [comment]
> ```./Setup.sh: line 178: nasm: command not found```

Please install all the dependencies
execute:
```sudo apt-get install nasm```

**Comment by negator92** [comment]
Thank you!
but now I see some new issue:
$  sudo ./Setup.sh 
Fetching Tarballs...
    automake-1.12.tar.gz...SKIPPED
    autoconf-2.65.tar.gz...SKIPPED
    binutils-2.26.tar.gz...SKIPPED
    gcc-5.3.0.tar.gz...SKIPPED
    newlib-1.19.0.tar.gz...SKIPPED
~/AtomOS/src/Build
~/AtomOS/src/Build
~/AtomOS/src/Build
Building Stuffs...
~/AtomOS/src/Build

and without sudo the same thing

**Comment by amaneureka** [comment]
Because setup was interrupted in between. It might be possible that some conflicts are made.
delete newlib directory from Bin folder. and execute ```./Setup.sh --newlib```

**Comment by negator92** [comment]
I delete and execute, than it says:
AtomOS/src/Build/Temp/newlib-1.19.0/newlib/doc/makedoc.c:1349:15: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     isp[0] = *(int *)(isp[0]);
               ^
i386-atomos-ar: creating libnosys.a
~/AtomOS/src/Build/Bin ~/AtomOS/src/Build
~/AtomOS/src/Build/Bin ~/AtomOS/src/Build
    Compiling gcc again
configure: WARNING: decimal float is not supported for this target, ignored
~/AtomOS/src/Build/Bin ~/AtomOS/src/Build
~/AtomOS/src/Build

**Comment by amaneureka** [comment]
Yes, this is expected behavior. Let it run completely

**Comment by negator92** [comment]
$  sudo ./Setup.sh 
Fetching Tarballs...
    automake-1.12.tar.gz...SKIPPED
    autoconf-2.65.tar.gz...SKIPPED
    binutils-2.26.tar.gz...SKIPPED
    gcc-5.3.0.tar.gz...SKIPPED
    newlib-1.19.0.tar.gz...SKIPPED
~/AtomOS/src/Build
~/AtomOS/src/Build
~/AtomOS/src/Build
Building Stuffs...
~/AtomOS/src/Build

and that's all

**Comment by amaneureka** [comment]
> ```$ sudo ./Setup.sh```

It should be ```sudo ./Setup.sh --newlib```

**Comment by negator92** [comment]
Sorry for my mistake. I do and have long output. Last strings are:
AtomOS/src/Build/Temp/newlib-1.19.0/newlib/doc/makedoc.c:1349:15: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
     isp[0] = *(int *)(isp[0]);
               ^
i386-atomos-ar: creating libnosys.a
~/AtomOS/src/Build/Bin ~/AtomOS/src/Build
~/AtomOS/src/Build/Bin ~/AtomOS/src/Build
    Compiling gcc again
~/AtomOS/src/Build/Bin ~/AtomOS/src/Build
~/AtomOS/src/Build

seems we already have such output

**Comment by amaneureka** [comment]
Did it exit without any error?

**Comment by negator92** [comment]
Only warnings, none of error

**Comment by amaneureka** [comment]
Great. It is completed then. Follow with further [build process](https://github.com/amaneureka/AtomOS/wiki/Build-Environment#building-libraries-est-30-mins)

**Comment by negator92** [comment]
Thank you again. I've builded libraries.
nasm, genisoimage were already installed, but next step I just do not know how to do.
what exactly shoul I do to "Build Atomix.Kernel_H and Atomixilc Projects"?
or I just should "Build.sh --mono"?
P.S. fust for your information, I should also notice that "Execute Build-cairo.sh" took more time that other steps.

**Comment by amaneureka** [comment]
> what exactly shoul I do to "Build Atomix.Kernel_H and Atomixilc Projects"?

Execute ```xbuild /p:Configuration=Release ./src/Atomix.sln```

And then execute ```Build.sh --mono```

**Comment by negator92** [comment]
"Execute xbuild /p:Configuration=Release ./src/Atomix.sln"
that step was finished without an error, only warnings about unused fields.
next step "Build.sh --mono" bring too much output. there were red strings:
"System.Exception: UnImplemented 'Blt_Un'
  at Atomixilc.IL.Blt_Un_il.Execute (Atomixilc.Options Config, Atomixilc.IL.OpCodeType xOp, System.Reflection.MethodBase method, Atomixilc.Optimizer Optimizer) <0x41061070 + 0x00543> in <filename unknown>:0 
  at Atomixilc.Compiler.ProcessMethod (System.Reflection.MethodBase method, Atomixilc.FunctionalBlock& block) <0x41052500 + 0x00e9b> in <filename unknown>:0 
  at Atomixilc.Compiler.ScanMethod (System.Reflection.MethodBase method) <0x4104d450 + 0x00207> in <filename unknown>:0 
  at Atomixilc.Compiler.Execute () <0x41049f80 + 0x002c3> in <filename unknown>:0 
  at Atomixilc.Program.Main (System.String[] args) <0x4103ed50 + 0x0009f> in <filename unknown>:0"
and folder Output consist only Kernel.asm file
Is it right?

**Comment by amaneureka** [comment]
Could you remove Apps folder from Bin directory. And re-run ```Build.sh --mono```

**Comment by negator92** [comment]
Done.
red strings:
"System.Exception: UnImplemented 'Blt_Un'
  at Atomixilc.IL.Blt_Un_il.Execute (Atomixilc.Options Config, Atomixilc.IL.OpCodeType xOp, System.Reflection.MethodBase method, Atomixilc.Optimizer Optimizer) <0x400bd070 + 0x00543> in <filename unknown>:0 
  at Atomixilc.Compiler.ProcessMethod (System.Reflection.MethodBase method, Atomixilc.FunctionalBlock& block) <0x400ae500 + 0x00e9b> in <filename unknown>:0 
  at Atomixilc.Compiler.ScanMethod (System.Reflection.MethodBase method) <0x400a9450 + 0x00207> in <filename unknown>:0 
  at Atomixilc.Compiler.Execute () <0x400a5f80 + 0x002c3> in <filename unknown>:0 
  at Atomixilc.Program.Main (System.String[] args) <0x4009ad50 + 0x0009f> in <filename unknown>:0"

**Comment by amaneureka** [comment]
That is not an expected output. Could you send me your Kernel.asm file?

**Comment by negator92** [comment]
http://www.mediafire.com/file/sxsji9y45hooxxo/Kernel.asm
done

**Comment by amaneureka** [comment]
Could you join me on IRC? ```#atomos @ freenote.net```

**Comment by amaneureka** [comment]
> "System.Exception: UnImplemented 'Blt_Un'

This problem has been reported on ```Mono 4.2.1.0```. Seems like something is wrong with that release. Added ```Mono JIT compiler version 4.8.0``` as Build requirement.
