### ISSUE TITLE
Crash on GenerateNewHashID()

### ISSUE THREAD

**Issue by jammln** [amaneureka/AtomOS#55]
The OS crashes with seg fault. After trying to copy the string that is generated by this function.
The Kernel.asm shows the function isn't complete.
I narrowed the issue down to .ToString() not seem to be working
Mono 4.8.0.0
Code:
`System_String_Atomix_Kernel_H_Gui_Window_GenerateNewHashID__:`
  `  push dword EBP`
 `   mov dword EBP, ESP`
 `   sub dword ESP, 0x8`
`    ; [Ldsflda] : OpField [0x0000-0x0005] System.UInt32 TicksFromStart => 0`
`    push dword static_Field__System_UInt32_Atomix_Kernel_H_Devices_Timer_TicksFromStart`
`    ; Unimplemented ILCode 'Constrained'`

This would result in the length of the string being > 4GB hence seg fault.
Fix for this was to change to `Convert.ToString(Timer.TicksFromStart)`
[Kernel.txt](https://github.com/amaneureka/AtomOS/files/842405/Kernel.txt)
GenerateNewHashID is in Window.cs in Gui

I think this is related to issue #4 and #5

**Comment by amaneureka** [comment]
Perfect. Yeah this is known issue which didn't crossed my mind.

**Comment by amaneureka** [comment]
I am making a quick fix like replacing it Convert.ToInt and adding error count at the end of log.

will follow up this issue on #5 

Thanks!
closing
